services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    container_name: trivia-app-backend
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/trivia
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  frontend:
    container_name: trivia-app-frontend
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://localhost:4000"
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongo-data:
